services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - deepsurf-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    ports:
      - 8000:8000
    networks:
      - deepsurf-network
    volumes:
      - backend-dbstore:/root/Deepsurf.ai/data
      - uploads:/root/Deepsurf.ai/uploads
      - ./config.toml:/root/Deepsurf.ai/config.toml:ro
    restart: unless-stopped

networks:
  deepsurf-network:

volumes:
  backend-dbstore:
  uploads:
